import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
//@ts-ignore
import { Widget } from '@rango-dev/widget-embedded'

import { SwapExplorerUrl } from 'rango-types'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const x = {description: "cc" , url: "sss"}
  console.log(x as SwapExplorerUrl)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
       <div>ddddd</div>
       <Widget />
      </main>
    </>
  )
}
